const ScreenNames = {
  MAIN: 'MAIN',
  BOTTOM_TABS: 'BOTTOM_TABS',
  HOME_TAB: 'HOME_TAB',
  HISTORY_TAB: 'HISTORY_TAB',
  NOTIFICATION_TAB: 'NOTIFICATION_TAB',
  PROFILE_TAB: 'PROFILE_TAB',

  HOME: 'HOME',
  HOME_DETAIL: 'HOME_DETAIL',
  HISTORY: 'HISTORY',
  PROFILE: 'PROFILE',
  PROFILE_DETAIL: 'PROFILE_DETAIL',
  NOTIFICATIONS: 'NOTIFICATIONS',
  NOTIFICATION_DETAIL: 'NOTIFICATION_DETAIL',
  ABOUT: 'ABOUT',
  ROOT_MODAL: 'ROOT_MODAL',
};

export default ScreenNames;
